mutation AddBet($game: ID, $participant: ID, $betStatus: ENUM_BETS_BETSTATUS) {
	createBet(
		input: {
			data: {
				betStatus: $betStatus
				participant: $participant
				game: $game
			}
		}
	) {
		bet {
			participant {
				name
				initials
				id
			}
			game {
				id
			}
			betStatus
		}
	}
}
