query GetInitialState {
	games(sort: "datetime:DESC") {
		id
		left {
			name
		}
		right {
			name
		}
		datetime
		left_score
		right_score
		bets {
			id
			participant {
				name
				initials
				id
			}
			betStatus
		}
	}
	participants {
		name
		initials
		id
	}
}
